---
- hosts: all
  become: true
  tasks:
    - name: Install apache and libapache2-mod-php packages
      apt:
        name: 
          - apache2
          - libapache2-mod-php 
        state: latest
        update_cache: yes
