---
- hosts: all
  become: true
  tasks:
    - name: Update repository index, install apache2 and php 
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
